# Generated by Django 5.0.6 on 2024-05-29 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_de_retiro', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_retiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono_inscripcion_whatsapp', models.CharField(max_length=20)),
                ('formulario_inscripcion', models.URLField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('casa_de_retiro', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='Emaus/Calendario/static/img/posters')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.ciudad')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.coordinador')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.pais')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.parroquia')),
            ],
        ),
        migrations.AddField(
            model_name='coordinador',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.parroquia'),
        ),
    ]
